name: Build

on: push

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Set env vars
        run: echo "TEMP_DIR=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"
      - name: Build with Gradle
        run: ./gradlew test

